# Generated by Django 4.2.30 on 2026-08-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
