# Generated by Django 4.2.30 on 2026-08-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='MobileFix Pro', max_length=255)),
                ('shop_phone', models.CharField(blank=True, max_length=50)),
                ('shop_address', models.TextField(blank=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
                ('currency', models.CharField(default='Rs.', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('job_prefix', models.CharField(default='JOB', max_length=10)),
            ],
        ),
    ]
