# Generated by Django 4.2.30 on 2026-08-10 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0004_alter_repairjob_assigned_technician_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_repairpart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='repair_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='repairs.repairjob'),
        ),
    ]
